# Generated by Django 2.2.2 on 2019-06-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsheading',
            name='id',
        ),
        migrations.AlterField(
            model_name='newsheading',
            name='read_more',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
